#!/bin/bash

echo "Hour of CI Setup Starting ..."


# Trust all Hour of CI notebooks to improve learner experience
# This enables us to auto-run code, initialize Markdown/code cells, etc.

# Gateway Lesson
for i in 1 2 3 4 5 6; do
    jupyter trust --generate-config gateway-lesson/gateway/gateway-$i.ipynb >> hci.log
done
jupyter trust --generate-config gateway-lesson/gateway/gateway-exploration.ipynb >> hci.log

echo "Please wait until setup is complete ..."


######Beginner######

# BD 
for i in 1 2 3; do
    jupyter trust --generate-config beginner-lessons/big-data/bigdata-$i.ipynb >> hci.log  
done
jupyter trust --generate-config beginner-lessons/big-data/bigdata-exploration.ipynb >> hci.log

# CT
for i in 1 2 3 4 5 6 7; do
    jupyter trust --generate-config beginner-lessons/computational-thinking/ct-$i.ipynb >> hci.log  
done

# CI
for i in 1 2 3 4 5; do
    jupyter trust --generate-config beginner-lessons/cyberinfrastructure/cyberinfrastructure-$i.ipynb >> hci.log  
done
jupyter trust --generate-config beginner-lessons/cyberinfrastructure/cyberinfrastructure-exploration.ipynb >> hci.log  

# GD
for i in 1 2 3 4 5 6; do
    jupyter trust --generate-config beginner-lessons/geospatial-data/gd-$i.ipynb >> hci.log
done
jupyter trust --generate-config beginner-lessons/geospatial-data/gd-example_1.ipynb >> hci.log 
jupyter trust --generate-config beginner-lessons/geospatial-data/gd-example_2.ipynb >> hci.log 

# IC
for i in 1 2 3 4 5; do
    jupyter trust --generate-config beginner-lessons/interdisciplinary-communication/ic-$i.ipynb >> hci.log 
done
jupyter trust --generate-config beginner-lessons/interdisciplinary-communication/ic-exploration.ipynb >> hci.log 

# PC
for i in 1 2 3 4; do
    jupyter trust --generate-config beginner-lessons/parallel-computing/pc-$i.ipynb >> hci.log 
done
jupyter trust --generate-config beginner-lessons/parallel-computing/pc-exploration.ipynb >> hci.log 

# SMA
for i in 1 2 3 4 5; do
    jupyter trust --generate-config beginner-lessons/spatial-modeling-analytics/sma-$i.ipynb >> hci.log  
done
jupyter trust --generate-config beginner-lessons/spatial-modeling-analytics/sma-exploration.ipynb >> hci.log  
jupyter trust --generate-config beginner-lessons/spatial-modeling-analytics/try_it1_sma.ipynb >> hci.log  
jupyter trust --generate-config beginner-lessons/spatial-modeling-analytics/try_it2_sma.ipynb >> hci.log  

# ST
for i in 1 2; do
    jupyter trust --generate-config beginner-lessons/spatial-thinking/st-$i.ipynb >> hci.log
done
jupyter trust --generate-config beginner-lessons/spatial-thinking/st-exploration.ipynb >> hci.log

######Intermediate#######

# BD 
for i in 1 2 3 4 5; do
    jupyter trust --generate-config intermediate-lessons/big-data/bigdata-$i.ipynb >> hci.log  
done
jupyter trust --generate-config intermediate-lessons/big-data/bigdata-exploration.ipynb >> hci.log

# CT
for i in 1 2 3 4 5 6; do
    jupyter trust --generate-config intermediate-lessons/computational-thinking/ct-$i.ipynb >> hci.log  
done

# CI
for i in 1 2 3 4 5 6; do
    jupyter trust --generate-config intermediate-lessons/cyberinfrastructure/cyberinfrastructure-$i.ipynb >> hci.log  
done
jupyter trust --generate-config intermediate-lessons/cyberinfrastructure/cyberinfrastructure-exploration.ipynb >> hci.log

# Geospatial Data Lesson
for i in 1 2 3 4 5; do
    jupyter trust --generate-config intermediate-lessons/geospatial-data/gd-$i.ipynb >> hci.log
done
jupyter trust --generate-config intermediate-lessons/geospatial-data/gd-exploration.ipynb >> hci.log 

# IC
for i in 1 2 3 4; do
    jupyter trust --generate-config intermediate-lessons/interdisciplinary-communication/ic-$i.ipynb >> hci.log 
done
jupyter trust --generate-config intermediate-lessons/interdisciplinary-communication/ic-exploration.ipynb >> hci.log 

# PC
for i in 1 2 3 4 5 6; do
    jupyter trust --generate-config intermediate-lessons/parallel-computing/pc-$i.ipynb >> hci.log 
done
jupyter trust --generate-config intermediate-lessons/parallel-computing/pc-exploration.ipynb >> hci.log 

# SMA
for i in 1 2 3 4 5 6; do
    jupyter trust --generate-config intermediate-lessons/spatial-modeling-analytics/sma-$i.ipynb >> hci.log  
done

# ST
for i in 1 2 3 4; do
    jupyter trust --generate-config intermediate-lessons/spatial-thinking/st-$i.ipynb >> hci.log
done
jupyter trust --generate-config intermediate-lessons/spatial-thinking/st-exploration.ipynb >> hci.log 

echo "Hour of CI Setup Complete!"
echo " "
echo "Please click on the arrow in the lower right corner to continue."